// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDopYg8b8biX-Bw1eT3OnFUW_-hRPHxNtI',
    appId: '1:995819487299:web:eff429daf54bececfd94f6',
    messagingSenderId: '995819487299',
    projectId: 'chatapp-a2c57',
    authDomain: 'chatapp-a2c57.firebaseapp.com',
    storageBucket: 'chatapp-a2c57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOD5-DRtPixXjzX6x8dMYj_FLNjljkcqs',
    appId: '1:995819487299:android:e4a69b68a89828f9fd94f6',
    messagingSenderId: '995819487299',
    projectId: 'chatapp-a2c57',
    storageBucket: 'chatapp-a2c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAby41vNPd5EnEkm7muNd8yQtektf5O31A',
    appId: '1:995819487299:ios:55e2b7807ff9ff4afd94f6',
    messagingSenderId: '995819487299',
    projectId: 'chatapp-a2c57',
    storageBucket: 'chatapp-a2c57.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAby41vNPd5EnEkm7muNd8yQtektf5O31A',
    appId: '1:995819487299:ios:55e2b7807ff9ff4afd94f6',
    messagingSenderId: '995819487299',
    projectId: 'chatapp-a2c57',
    storageBucket: 'chatapp-a2c57.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDopYg8b8biX-Bw1eT3OnFUW_-hRPHxNtI',
    appId: '1:995819487299:web:71ac6155ae91b9c3fd94f6',
    messagingSenderId: '995819487299',
    projectId: 'chatapp-a2c57',
    authDomain: 'chatapp-a2c57.firebaseapp.com',
    storageBucket: 'chatapp-a2c57.firebasestorage.app',
  );
}
